### ISSUE TITLE
Should minimum array size be greater than 0 to prevent empty bars

### ISSUE THREAD

**Issue by rwinterstein** [FranciscoSerrano/sorting-algorithms#6]
Example of 0's being generated in the array causing gaps

<img width="885" alt="Screen Shot 2021-04-10 at 9 46 14 AM" src="https://user-images.githubusercontent.com/18250822/114271873-987dba80-99e1-11eb-909e-f6e1ba23c3ad.png">

**Comment by FranciscoSerrano** [comment]
Yup thats super easy. All I did was change 
`for (let i = 0; i < size; i++) {
        array.push(Math.floor(Math.random() * max_value));
    }`
to this:
'for (let i = 0; i < size; i++) {
        array.push(Math.floor(Math.random() * max_value) + 5);
    }'
The minimum should be 5 now.
